sudo: required
services:
    - docker
language: go
go:
  - 1.15.x
env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
script:
 - make test
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    make flannel-git;
    fi
notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:wireguard/wireguard'
    packages:
      - wireguard
      - linux-headers-$(uname -r)
